### PR TITLE
#53 wallet address

### PR DESCRIPTION
**Pull request by bachstatter**
This lets you add a custom wallet address for viewing purposes.

1. Go to `/walletAddress`
2. Click on your wallet
Screen Shot 2019-11-16 at 12 22 08 pm
3. Add the wallet you want to view
Screen Shot 2019-11-16 at 12 22 40 pm

Dev improvement:
I added styled component plugin, this is a big improvement for dev.  Generated classname get readable and it adds display name to components so they show up with names in react devtools

### CODE REVIEW

**Comment by bachstatter** [comment]
I just realized I missed translation for the `Add` text inside the add button. Not sure if this is needed since this is an adminy feature

**Comment by justinjmoses** [comment]
Yes @bachstatter, also for the `placeholder` text..

I actually think we should consider moving the actual translations themselves into this repo and using `synthetix-translations` as a way to standardize how translations are stored and read. That would mean this PR could also contain the EN translations for these features.

**Comment by bachstatter** [comment]
@justinjmoses  I think if we want to change the translation architecture that could happen in a new PR? I've pushed changed to use translation both for the button text and the placeholder.

I didn't have commit access to [synthetix-translation](https://github.com/Synthetixio/synthetix-translations) package but I created a PR:
https://github.com/Synthetixio/synthetix-translations/pull/14

That PR should be merged before this one gets merged.

**Comment by justinjmoses** [comment]
Yes, my comment was more to Clem about improving this workflow. We will make a decision on this today, but we can do it after we’ve merged your PRs

**Pull request merged**
