### PR TITLE
68 total row

### PR DESCRIPTION
**Pull request by bachstatter**
Screen Shot 2019-12-07 at 4 50 39 pm
#68

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@bachstatter I don't think this is the correct area!  It should be in the Escrow (staking rewards) tab.

Sorry we should have provided more info for that one. (cc @hav-noms )

**Comment by bachstatter** [comment]
Ah damn it, I was a bit confused but thought the screenshot might've been from the old version.

Should be easy to move the logic though!

**Comment by clementbalestrat** [comment]
Yes! The logic should be simpler actually. Sorry again!

**Comment by bachstatter** [comment]
I'm still not 100% sure where this table is. Is it the vesting table under the escrow tab? it looks quite different from the screenshot in #68. No sUSD etc.

**Comment by clementbalestrat** [comment]
Go to the wallet you’ve claimed the rewards from. You will see a table

**Comment by bachstatter** [comment]
Screen Shot 2019-12-08 at 4 51 01 pm
That table already got a total?

**Comment by clementbalestrat** [comment]
Closing this one.

**Pull request closed without merging**
