### PR TITLE
Calculate estimated C-ratio

### PR DESCRIPTION
**Pull request by bachstatter**
Screen Shot 2019-12-04 at 8 27 27 am
Screen Shot 2019-12-04 at 8 27 36 am

### CODE REVIEW

**Comment by bachstatter** [comment]
Before merging I should probably check is mintAmount is invalid...

**Comment by bachstatter** [comment]
Should be ready. We could be really fancy and subtract gas price bit I dont think that's neccessary

**Comment by clementbalestrat** [comment]
@bachstatter great! What do you mean by subtracting gas price?

**Comment by clementbalestrat** [comment]
@bachstatter there is an issue. We should display current c-ratio when the input is 0, '', or has incorrect number.

Screen Shot 2019-12-04 at 5 16 26 pm

**Pull request merged**
