### PR TITLE
Display staked univ1

### PR DESCRIPTION
**Pull request by ItsNickBarry**
Both staked and held LP token balances should be displayed.

### CODE REVIEW

**Comment by clementbalestrat** [comment]
@ItsNickBarry thanks! can you please make this PR to `dev` instead and make sure your branch is up-to-date?

**Comment by ItsNickBarry** [comment]
@clementbalestrat I've updated the target branch and there do not appear to be conflicts.

**Comment by ItsNickBarry** [comment]
@clementbalestrat I changed the target branch to `dev` but it's out-of-date, so all of the subsequent commits to `master` are included in this pull request.  I tried to rebase my commits onto `dev`, but doing so would cause merge conflicts both during the rebase and the later merge with `master` due to 558cdf34e74fac9457ee71f9f4ecd6e8edc0a740.

**Comment by clementbalestrat** [comment]
@ItsNickBarry all good I'll just merge it to staging then!

**Pull request merged**
